import streamlit as st
import pandas as pd
from pathlib import Path

# Resolve path relative to this file — works on any machine
BASE_DIR = Path(__file__).resolve().parent.parent # go up one level from src/ to project root
DATA_PATH = BASE_DIR / "data" / "processed" / "alerts.csv" # this file is generated by the pipeline and contains the final results with anomaly detection and alert generation, which the dashboard will load to display insights and visualizations. The path is constructed using pathlib to ensure it works across different operating systems and environments, and it points to the processed data directory where the alerts.csv file is saved after running the full pipeline.
# Set up the Streamlit dashboard with a title and page configuration, load the processed data containing anomaly detection results and generated alerts, and display key performance indicators (KPIs) such as total records, number of anomalies detected, anomaly rate, and the most common alert type. The dashboard also includes visualizations of sensor trends over time, a breakdown of anomaly alert types, and a detailed table of anomaly alerts with filtering options for exploring the data.
st.set_page_config(page_title="Predictive Maintenance", layout="wide")
st.title("Smart IoT Predictive Maintenance System")

# Load data with anomaly detection results and generated alerts, which is expected to be saved at data/processed/alerts.csv after running the full pipeline. If the file is not found, display an error message prompting the user to run the pipeline first to generate the necessary data for the dashboard, and stop execution to prevent further errors.
if not DATA_PATH.exists():
    st.error(f"Data file not found at {DATA_PATH}. Run the pipeline first:\n"
             "python src/data_generator.py → preprocessing.py → anomaly_detection.py → alerts.py") # Check if the expected data file exists at the specified path. If it does not exist, display an error message in the Streamlit dashboard indicating that the data file is missing and providing instructions to run the full pipeline to generate the necessary data. After displaying the error message, stop further execution of the dashboard using st.stop() to prevent any additional errors that would occur from trying to load a non-existent file or work with missing data.
    st.stop() # Stop further execution of the Streamlit dashboard after displaying the error message about the missing data file, to prevent any additional errors that would occur from trying to load a non-existent file or work with missing data. This ensures that the user is informed about the issue and can take the necessary steps to run the pipeline and generate the required data before attempting to use the dashboard again.

df = pd.read_csv(DATA_PATH)
anomalies = df[df['anomaly'] == -1] # Filter the DataFrame to include only rows where the 'anomaly' column is -1, which indicates that an anomaly was detected by the Isolation Forest model. This subset of the data will be used for generating insights and visualizations related to the anomalies and their associated alerts in the dashboard. The resulting 'anomalies' DataFrame will contain only the records that were flagged as anomalous, allowing for focused analysis on these critical events.

# KPI metrics calculation and display
total = len(df) # Calculate the total number of records in the DataFrame, which represents the total number of sensor readings or data points that were processed and analyzed for anomaly detection and alert generation. This metric will be displayed in the dashboard as a key performance indicator (KPI) to provide context on the scale of the data being analyzed and to help users understand the proportion of anomalies detected relative to the total dataset. The 'total' variable will be used in conjunction with the number of anomalies detected to calculate the anomaly rate and provide insights into the overall health of the system being monitored.
n_anomalies = len(anomalies) # Calculate the number of anomalies detected by counting the number of rows in the 'anomalies' DataFrame, which contains only the records that were flagged as anomalous (where 'anomaly' == -1). This metric represents the total count of anomalous events that were identified in the dataset based on the Isolation Forest model's predictions. The 'n_anomalies' variable will be displayed in the dashboard as a key performance indicator (KPI) to inform users about the number of critical events that were detected, and it will also be used to calculate the anomaly rate as a percentage of the total records, providing insights into the frequency of anomalies in the monitored system.
anomaly_rate = n_anomalies / total * 100 # Calculate the anomaly rate as a percentage by dividing the number of anomalies detected (n_anomalies) by the total number of records (total) and multiplying by 100. This metric provides insight into the proportion of anomalous events relative to the overall dataset, allowing users to understand how frequently anomalies are occurring in the monitored system. The 'anomaly_rate' variable will be displayed in the dashboard as part of the key performance indicators (KPIs) to help users assess the health and stability of the system being analyzed, and it can also be used to track changes in anomaly frequency over time or after implementing maintenance actions.
# Determine the most common alert type among the detected anomalies by counting the occurrences of each unique alert message in the 'alert' column of the 'anomalies' DataFrame and identifying the one with the highest count. This metric provides insight into which specific issues or conditions are most frequently associated with the detected anomalies, allowing users to prioritize maintenance actions or further investigate the underlying causes of these common alerts. The 'top_alert' variable will be displayed in the dashboard as a key performance indicator (KPI) to inform users about the most prevalent type of alert generated from the anomalies, helping them focus on addressing the most critical and frequent issues in their predictive maintenance efforts.
top_alert = (
    anomalies['alert'] 
    .value_counts() # Count the occurrences of each unique alert message in the 'alert' column of the 'anomalies' DataFrame, which contains only the records that were flagged as anomalous. This step aggregates the data to determine how many times each specific alert type was generated from the detected anomalies, providing insight into which issues or conditions are most commonly associated with the anomalous events in the dataset.
    .idxmax() if n_anomalies > 0 else "None" # Identify the alert message with the highest count using idxmax(), which returns the index (alert message) of the first occurrence of the maximum count. This step determines which specific alert type is the most prevalent among the detected anomalies, allowing users to understand which issues are most frequently occurring in their system. If there are no anomalies detected (n_anomalies == 0), set 'top_alert' to "None" to indicate that there are no alerts to report, ensuring that the dashboard can handle cases where no anomalies are present without causing errors or displaying misleading information. The resulting 'top_alert' variable will be displayed in the dashboard as a key performance indicator (KPI) to inform users about the most common type of alert generated from the anomalies, helping them focus on addressing the most critical and frequent issues in their predictive maintenance efforts.
)
# Display the calculated KPIs in the Streamlit dashboard using metric components, showing total records, number of anomalies detected, anomaly rate as a percentage of total records, and the most common alert type among the detected anomalies. The metrics are displayed in a row with four columns for better visualization and organization of the key performance indicators (KPIs) related to the anomaly detection results and generated alerts.
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Records", f"{total:,}")
col2.metric("Anomalies Detected", n_anomalies, delta=f"{anomaly_rate:.1f}% of total", delta_color="inverse")
col3.metric("Normal Records", total - n_anomalies)
col4.metric("Top Alert Type", top_alert.split("→")[-1].strip() if "→" in top_alert else top_alert)
# Add a divider in the Streamlit dashboard to visually separate the KPI section from the subsequent visualizations and data tables, improving the layout and readability of the dashboard by creating a clear distinction between different sections of content.
st.divider()
# Sensor trends using real sensor unit columns (not Z-scores) if available, with a fallback to scaled values if raw columns are missing. This section of the dashboard visualizes the trends of the original sensor readings (temperature, vibration, pressure) over time using line charts. If the raw sensor columns (temperature_raw, vibration_raw, pressure_raw) are present in the DataFrame, they will be used for the visualization to show the actual sensor values in their original units. If the raw columns are not found, a warning message is displayed to inform the user that the dashboard is showing scaled Z-scores instead, and the line charts will use the scaled values from the 'temperature', 'vibration', and 'pressure' columns. This allows users to still visualize trends in the data even if the raw sensor readings are not available, while also providing context about what is being displayed.
st.subheader("Sensor Trends (original units)")
# Check if raw sensor columns are available in the DataFrame. If they are, use them for the line chart to show actual sensor values in original units. If not, display a warning and fall back to using the scaled Z-score columns for visualization, while informing the user about the change in displayed data.
raw_cols = ['temperature_raw', 'vibration_raw', 'pressure_raw']
if all(c in df.columns for c in raw_cols):
    chart_df = df[raw_cols].rename(columns={
        'temperature_raw': 'Temperature (°C)',
        'vibration_raw': 'Vibration (mm/s)',
        'pressure_raw': 'Pressure (bar)'
    })
else:
    # Fallback to scaled values with a warning if raw sensor columns are not found in the DataFrame, which may occur if the data was generated without including the original sensor readings or if there was an issue in the data processing pipeline. In this case, display a warning message in the dashboard to inform the user that the raw sensor columns are not available and that the line charts will show scaled Z-scores instead. This ensures that users are aware of what is being visualized and can interpret the charts accordingly, while still allowing them to see trends in the data even without access to the original sensor units.
    st.warning("Raw sensor columns not found — showing scaled Z-scores. Re-run the pipeline to get real units.")
    chart_df = df[['temperature', 'vibration', 'pressure']]

st.line_chart(chart_df) # Visualize the trends of the sensor readings over time using a line chart, which allows users to see how the values of temperature, vibration, and pressure change across the dataset. The line chart will use either the raw sensor columns (if available) or the scaled Z-score columns (if raw columns are missing) to provide insights into the behavior of the monitored system and help identify any patterns or anomalies in the sensor data.

# Anomaly distribution and alert breakdown
st.subheader("Anomaly alert breakdown")
# If there are anomalies detected, display a bar chart showing the distribution of alert types among the detected anomalies. If no anomalies are detected, display an informational message indicating that no anomalies were found, which helps users understand that there are no critical events to report and that the system is currently operating within normal parameters. This conditional display ensures that the dashboard provides relevant insights based on the presence or absence of anomalies in the dataset.
if n_anomalies > 0:
    alert_counts = anomalies['alert'].value_counts().reset_index()
    alert_counts.columns = ['Alert type', 'Count']
    st.bar_chart(alert_counts.set_index('Alert type'))
else:
    st.info("No anomalies detected.")

# Anomaly alerts table with raw sensor readings if available, and a filter to explore all records, only anomalies, or only normal records. This section of the dashboard provides a detailed view of the anomaly alerts, including the original sensor readings (if available) for reference. The table allows users to explore the data in more depth by filtering to show all records, only the detected anomalies, or only the normal records, enabling them to analyze the specific conditions associated with the anomalies and understand the context of the alerts generated from the anomaly detection process.
st.subheader("Anomaly alerts detail")
# Determine which columns to display in the anomaly alerts table, prioritizing raw sensor readings if they are available in the DataFrame. If the raw sensor columns (temperature_raw, vibration_raw, pressure_raw) are present, they will be included in the display along with the timestamp and alert message. If the raw columns are not found, the table will fall back to showing the scaled values (temperature, vibration, pressure) along with the alert message. This allows users to see the most informative data available for each anomaly alert while providing context about what is being displayed.
display_cols = [c for c in ['timestamp', 'temperature_raw', 'vibration_raw', 'pressure_raw', 'alert']
                if c in anomalies.columns]
# If raw sensor columns are not found in the anomalies DataFrame, display a warning message to inform the user that the table will show scaled Z-scores instead of original sensor readings, and adjust the display columns accordingly to show the available data.
if not display_cols:
    display_cols = ['temperature', 'vibration', 'pressure', 'alert']
# Display the anomaly alerts table in the Streamlit dashboard, showing either the raw sensor readings (if available) or the scaled Z-scores (if raw columns are missing) along with the alert messages. The table is displayed using st.dataframe, which allows for interactive exploration of the data, and it is set to use the full container width for better visibility of the content.    
st.dataframe(
    anomalies[display_cols].rename(columns={
        'temperature_raw': 'Temperature (°C)',
        'vibration_raw': 'Vibration (mm/s)',
        'pressure_raw': 'Pressure (bar)'
    }),
    use_container_width=True # Set the table to use the full width of the container for better visibility of the content, allowing users to see more columns without horizontal scrolling and improving the overall readability of the anomaly alerts data displayed in the dashboard.
)

# Filter to explore all records, only anomalies, or only normal records in the data table. This feature allows users to easily switch between different views of the dataset, enabling them to focus on specific subsets of the data for analysis. By selecting "Only anomalies", users can see just the records that were flagged as anomalous, while "Only normal" will show the records that were not flagged as anomalies. The "All records" option provides a comprehensive view of the entire dataset, allowing users to compare normal and anomalous records side by side. This interactive filtering enhances the usability of the dashboard and helps users gain deeper insights into the conditions associated with anomalies and normal operations.
st.subheader("Explore data")
option = st.selectbox("Show", ["All records", "Only anomalies", "Only normal"])
# Display the data table based on the selected filter option, allowing users to explore all records, only the detected anomalies, or only the normal records. The table will adjust dynamically based on the user's selection, providing an interactive way to analyze the dataset and understand the specific conditions associated with anomalies and normal operations in the monitored system.
if option == "Only anomalies":
    st.dataframe(anomalies, use_container_width=True)
elif option == "Only normal":
    st.dataframe(df[df['anomaly'] == 1], use_container_width=True)
else:
    st.dataframe(df, use_container_width=True)
